### ISSUE TITLE
Boolean operation segfault

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#136]
Apply the following patch:
```diff
diff --git a/tools/perf_test.cpp b/tools/perf_test.cpp
index 2ad385a..c002aa0 100644
--- a/tools/perf_test.cpp
+++ b/tools/perf_test.cpp
@@ -23,7 +23,6 @@ int main(int argc, char **argv) {
   for (int i = 0; i < 8; ++i) {
     Manifold sphere = Manifold::Sphere(1, (8 << i) * 4);
     Manifold sphere2 = sphere;
-    sphere2.Translate(glm::vec3(0.5));
     auto start = std::chrono::high_resolution_clock::now();
     Manifold diff = sphere - sphere2;
     auto end = std::chrono::high_resolution_clock::now();
```

And run `perfTest` with `CPP` backend, it will segfault after n=8192. With address sanitizer enabled:
```
nTri = 512, time = 0.0255094 sec
nTri = 2048, time = 0.101124 sec
nTri = 8192, time = 0.321662 sec
=================================================================
==1540173==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6310002a87f4 at pc 0x00000056519a bp 0x7ffdeba3df50 sp 0x7ffdeba3df48
WRITE of size 4 at 0x6310002a87f4 thread T0
    #0 0x565199 in manifold::Manifold::Impl::RemoveIfFolded(int) /home/pca006132/code/test/manifold/manifold/src/edge_op.cpp:211:50
    #1 0x564728 in manifold::Manifold::Impl::FormLoop(int, int) /home/pca006132/code/test/manifold/manifold/src/edge_op.cpp:193:3
    #2 0x560e31 in manifold::Manifold::Impl::CollapseEdge(int) /home/pca006132/code/test/manifold/manifold/src/edge_op.cpp:294:9
    #3 0x55e2a2 in manifold::Manifold::Impl::SimplifyTopology() /home/pca006132/code/test/manifold/manifold/src/edge_op.cpp:131:39
    #4 0x59ae56 in manifold::Boolean3::Result(manifold::Manifold::OpType) const /home/pca006132/code/test/manifold/manifold/src/boolean_result.cpp:690:8
    #5 0x509601 in manifold::Manifold::Boolean(manifold::Manifold const&, manifold::Manifold::OpType) const /home/pca006132/code/test/manifold/manifold/src/manifold.cpp:466:50
    #6 0x509b8d in manifold::Manifold::operator-(manifold::Manifold const&) const /home/pca006132/code/test/manifold/manifold/src/manifold.cpp:489:10
    #7 0x5039bd in main /home/pca006132/code/test/manifold/tools/perf_test.cpp:27:28
    #8 0x7fc9f51c078f in __libc_start_main (/nix/store/qjgj2642srlbr59wwdihnn66sw97ming-glibc-2.33-123/lib/libc.so.6+0x2778f)
    #9 0x423279 in _start /build/glibc-2.33/csu/../sysdeps/x86_64/start.S:120

0x6310002a87f4 is located 12 bytes to the left of 68688-byte region [0x6310002a8800,0x6310002b9450)
allocated by thread T0 here:
    #0 0x4c9497 in __interceptor_malloc (/home/pca006132/code/test/manifold/buildCPP/tools/perfTest+0x4c9497)
    #1 0x5642b9 in manifold::ManagedVec<glm::vec<3, float, (glm::qualifier)0> >::mallocManaged(glm::vec<3, float, (glm::qualifier)0>**, unsigned long) /home/pca006132/code/test/manifold/utilities/include/vec_dh.h:257:36
    #2 0x5642b9 in manifold::ManagedVec<glm::vec<3, float, (glm::qualifier)0> >::reserve(unsigned long) /home/pca006132/code/test/manifold/utilities/include/vec_dh.h:158:7
    #3 0x5642b9 in manifold::ManagedVec<glm::vec<3, float, (glm::qualifier)0> >::push_back(glm::vec<3, float, (glm::qualifier)0> const&) /home/pca006132/code/test/manifold/utilities/include/vec_dh.h:186:7
    #4 0x5642b9 in manifold::VecDH<glm::vec<3, float, (glm::qualifier)0> >::push_back(glm::vec<3, float, (glm::qualifier)0> const&) /home/pca006132/code/test/manifold/utilities/include/vec_dh.h:417:40
    #5 0x5642b9 in manifold::Manifold::Impl::FormLoop(int, int) /home/pca006132/code/test/manifold/manifold/src/edge_op.cpp:178:12
    #6 0x560e31 in manifold::Manifold::Impl::CollapseEdge(int) /home/pca006132/code/test/manifold/manifold/src/edge_op.cpp:294:9

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/pca006132/code/test/manifold/manifold/src/edge_op.cpp:211:50 in manifold::Manifold::Impl::RemoveIfFolded(int)
```

**Comment by elalish** [comment]
Sounds like this may be related to #109.
